import { chromium } from 'playwright'
import { writeFile } from 'node:fs/promises'

const browser = await chromium.launch({ headless: true })
const context = await browser.newContext()
const page = await context.newPage()
page.setDefaultTimeout(3000)
page.on('console', (message) => console.log('console', message.type(), message.text()))
page.on('pageerror', (error) => console.log('pageerror', error.message))
console.log('goto')
await page.goto('http://localhost:5173/#/dunhuang/home')
const intro = page.locator('.intro-screen')
if (await intro.isVisible().catch(() => false)) {
  console.log('intro')
  const earth = page.getByRole('button', { name: /跳过地球动画/ })
  if (await earth.isVisible().catch(() => false)) await earth.click()
  const video = page.getByRole('button', { name: /跳过视频/ })
  if (await video.isVisible().catch(() => false)) await video.click()
  await page.locator('.location-option').first().waitFor()
  await page.locator('.location-option').first().click()
  const destination = page.getByRole('button', { name: /跳过视频/ })
  if (await destination.isVisible().catch(() => false)) await destination.click()
  await intro.waitFor({ state: 'hidden' })
}
console.log('select')
await page.getByRole('button', { name: '选关', exact: true }).click()
console.log('start')
await page.getByRole('button', { name: '开始所选关卡' }).click()
console.log('started', await page.url(), await page.evaluate(() => ({ keys: Object.keys(localStorage), value: localStorage.getItem('dunhuang-mystery:game:v1') })))
await page.locator('.panorama-hotspot').first().click()
await page.getByRole('button', { name: '开启谜题' }).click()
await page.locator('.answer-option').first().click()
await page.getByRole('button', { name: '查看本卷结果' }).click()
await page.getByRole('button', { name: '关闭题目' }).click()
console.log('before reload', await page.evaluate(() => ({ keys: Object.keys(localStorage), value: localStorage.getItem('dunhuang-mystery:game:v1') })))
await writeFile('/tmp/dunhuang-snapshot.json', await page.evaluate(() => localStorage.getItem('dunhuang-mystery:game:v1') ?? ''))
await page.reload()
await page.waitForTimeout(500)
console.log('after reload', await page.url(), await page.evaluate(() => ({ keys: Object.keys(localStorage), value: localStorage.getItem('dunhuang-mystery:game:v1') })))
console.log('heading', await page.getByRole('heading', { level: 1 }).innerText(), 'error', await page.locator('.persistence-error').textContent().catch(() => null))
await browser.close()
