import { test, expect } from '@playwright/test'

test('desktop and mobile visual checks', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '开始', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('home-desktop.png'), fullPage: true })
  await expect(page.getByRole('button')).toHaveCount(2)
  await page.getByRole('button', { name: '选关', exact: true }).click()
  await expect(page).toHaveURL(/\/levels$/)
  await expect(page.locator('.chapter-card')).toHaveCount(3)
  await page.screenshot({ path: testInfo.outputPath('selection-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('selection-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: '返回主菜单' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('home-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '开始', exact: true }).click()
  await expect(page.locator('.panorama-status')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('game-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: '开启谜题', exact: true }).click()
  await expect(page.locator('.answer-option')).toHaveCount(4)
  await page.screenshot({ path: testInfo.outputPath('question-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})
